# Generated by Django 4.2.7 on 2024-07-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0050_workercontact_status_alter_workercontact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workercontact",
            name="status",
            field=models.CharField(
                choices=[
                    ("1 per week", "1 per week"),
                    ("2 per week", "2 per week"),
                    ("3 per week", "3 per week"),
                ],
                max_length=20,
                null=True,
                verbose_name="No of Classes",
            ),
        ),
    ]
