# Generated by Django 4.2.7 on 2024-07-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0051_alter_workercontact_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workercontact",
            name="description",
            field=models.TextField(verbose_name="Course"),
        ),
    ]
